[build]
builder = "dockerfile" 
dockerfile = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx prisma generate --schema=prisma/schema.postgresql.prisma && npx prisma db push --schema=prisma/schema.postgresql.prisma && node dist/index.js'"